name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: swt2
          POSTGRES_DB: swt2
          POSTGRES_PASSWORD: swt2
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U swt2 -d swt2"
          --health-timeout=60s
          --health-interval=15s
          --health-retries=5

    steps:
      # 1
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
           fetch-depth: 0   
     
      # 2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
           distribution: 'zulu'
           java-version: '17'
           
      # 3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      # 4
      - name: Build backend project
        working-directory: ./bogenliga
        run: |
          java -version
          export MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED"
          mvn clean -T 1C

      # 5
      - name: Run backend tests
        working-directory: ./bogenliga
        run: |
          mvn test  

      # 6
      - name: Start backend
        working-directory: ./bogenliga
        run: |
          mvn spring-boot:run &

      # 7
      - name: Clone frontend repository
        uses: actions/checkout@v2
        with:
          repository: aminaacid/bogenliga_bbf  
          token: ${{ secrets.GITHUB_TOKEN }}   

      # 8
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      # 9
      - name: Install frontend dependencies
        working-directory: ./bogenliga
        run: |
          npm install

      # 10
      - name: Build frontend
        working-directory: ./bogenliga
        run: |
          npm run build  
      

      # 12
      - name: Start frontend
        working-directory: ./bogenliga
        run: |
          npm start &  

      # 13
      - name: Build completion
        if: success()
        run: echo "Build and tests completed successfully!"
