name: Cypress Tests
on:
  workflow_run:
    workflows: ["Build"] 
    types:
      - completed

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install Cypress
      - name: Install Cypress
        working-directory: ./bogenliga_bbf/bogenliga
        run: |
          npm install cypress@14.0.0

      # 4. Install XVFB
      - name: Install XVFB
        run: sudo apt-get install xvfb

      # 5. Run Cypress tests
      - name: Run Cypress tests
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npx cypress run --browser chrome --record --parallel --key ${{ secrets.CYPRESS_RECORD_KEY }} --config-file ./bogenliga_bbf/bogenliga/cypress.config.ts
