name: PostgreSQL
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: swt2 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Connect to PostgreSQL
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432      
          POSTGRES_USER: swt2      
          POSTGRES_DB: swt2        
          POSTGRES_PASSWORD: swt2  
          JWT_SECRET: secret-key         
          JWT_EXPIRATION: 3600000        
          JWT_REFRESH: 10                
          FLYWAY_LOCATIONS: classpath:db/migration/all,classpath:db/migration/LOCAL
          FLYWAY_CLEAN_ENABLED: false     
          LOGGING_LEVEL_ROOT: WARN
          LOGGING_LEVEL_APPLICATION: DEBUG
          LOGGING_LEVEL_SPRING_WEB: DEBUG
